trigger: none

pr:
  branches:
    include:
    - main
    - release/*
  paths:
    include:
    - /Worker.Extension.Sql/

extends:
  template: ../builds/azure-pipelines/extensions-ci.yml
  parameters:
    ExtensionDirectory: /Worker.Extension.Sql