trigger: none

pr: none

schedules:
  - cron: "0 0 * * *"
    displayName: Mon-Fri at Midnight
    branches:
      include:
        - main
    always: true

variables:
  configuration: 'Release'
  serverPassword: ''
  nodeModulesPath: ''
  LGTM.UploadSnapshot: true
  Semmle.SkipAnalysis: true

stages:
- stage: BuildPublish
  displayName: 'Release Build and Publish'

  jobs:
  - job: BuildTest
    displayName: 'Build and Test on '
    timeoutInMinutes: '120'
    strategy:
      matrix:
        # Disabling performance tests on macOS due to issues with running MSSQL on Docker
        # We need to set up a self-hosted agent with Docker running by default: https://github.com/microsoft/azure-pipelines-tasks/issues/12823
        # mac:
        #   imageName: 'macos-latest'
        #   testServer: ''
        windows:
          imageName: 'windows-latest'
          testServer: '(LocalDb)\MSSQLLocalDB'
        linux:
          imageName: 'ubuntu-latest'
          testServer: ''

    pool:
      vmImage: '$(imageName)'

    workspace:
      clean: all

    steps:
      - template: 'template-steps-performance.yml'
        parameters:
          configuration: '$(configuration)'
