# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

import azure.functions as func
from Common.productdefaultpkanddifferentcolumnorder import ProductDefaultPKAndDifferentColumnOrder


# This shows an example of a SQL Output binding where the target table has a default primary key
# of type uniqueidentifier and the column is not included in the output object. The order of the
# properties in the POCO is different from the order of the columns in the SQL table. A new row will
# be inserted and the uniqueidentifier will be generated by the engine.
def main(req: func.HttpRequest, product: func.Out[func.SqlRow]) -> func.HttpResponse:
    row = func.SqlRow(ProductDefaultPKAndDifferentColumnOrder(
        100,
        "test")
    )
    product.set(row)

    return func.HttpResponse(
        body=row.to_json(),
        status_code=201,
        mimetype="application/json"
    )
