# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

using namespace System.Net

# This shows an example of a SQL Output binding where the target table has a default primary key
# of type uniqueidentifier and the column is not included in the output object. The order of the
# properties in the POCO is different from the order of the columns in the SQL table. A new row will
# be inserted and the uniqueidentifier will be generated by the engine.
param($Request, $TriggerMetadata)

$req_query = @{
    Cost=100;
    Name="test";
};

Push-OutputBinding -Name product -Value $req_query

Push-OutputBinding -Name response -Value ([HttpResponseContext]@{
    StatusCode = [HttpStatusCode]::OK
    Body = $req_query
})