name: On Label
on:
  issues:
    types: [labeled]

jobs:
  processLabelAction:
    name: Process Label Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - name: Process Label Action
        uses: hramos/label-actions@907a3b876f2d94007f0a4009390fd0e3e156450c # v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      issues: write
