name: On Label
on:
  issues:
    types: [labeled]

jobs:
  processLabelAction:
    name: Process Label Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Process Label Action
        uses: hramos/label-actions@a366dfe725db739c4522391dd1cb3daa9cb399d5 # v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      issues: write
